---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Nextcloud PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/bitnami/postgresql:13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: nextcloud
        - name: POSTGRES_DB
          value: nextcloud
        - name: PGDATA
          value: /bitnami/postgresql/data
        volumeMounts:
        - name: postgres-data
          mountPath: /bitnami/postgresql
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
---
# Nextcloud Apache Config ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-apache-config
data:
  ports.conf: |
    # Listen on high port instead of 80
    Listen 8080
  000-default.conf: |
    <VirtualHost *:8080>
      DocumentRoot /var/www/html
      ServerName nextcloud-ryan-nix-dev.apps.rm3.7wse.p1.openshiftapps.com
      
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
      
      <Directory /var/www/html/>
        Options FollowSymlinks MultiViews
        AllowOverride All
        Require all granted
      </Directory>
    </VirtualHost>
---
# Nextcloud Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: docker.io/library/nextcloud:28.0.1-apache
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: nextcloud
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: admin123
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "localhost nextcloud-ryan-nix-dev.apps.rm3.7wse.p1.openshiftapps.com *"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: OVERWRITEHOST
          value: "nextcloud-ryan-nix-dev.apps.rm3.7wse.p1.openshiftapps.com"
        - name: OVERWRITEWEBROOT
          value: "/"
        - name: OVERWRITECONDADDR
          value: "^.*$"
        - name: PHP_MEMORY_LIMIT
          value: "512M"
        - name: APACHE_CONFDIR
          value: /etc/apache2
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        - name: apache-config
          mountPath: /etc/apache2/ports.conf
          subPath: ports.conf
        - name: apache-config
          mountPath: /etc/apache2/sites-available/000-default.conf
          subPath: 000-default.conf
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Modified Apache configuration to use port 8080 instead of 80"
            cat /etc/apache2/ports.conf
            cat /etc/apache2/sites-available/000-default.conf
            
            # Start Apache with the modified configuration
            exec /entrypoint.sh apache2-foreground
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 1
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-pvc
      - name: apache-config
        configMap:
          name: nextcloud-apache-config
---
# Nextcloud Service
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: nextcloud
---
# Nextcloud Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  host: nextcloud-ryan-nix-dev.apps.rm3.7wse.p1.openshiftapps.com
  to:
    kind: Service
    name: nextcloud
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect